# Generated by Django 5.1.11 on 2025-08-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Indica se o produto está disponível para venda'),
        ),
    ]
